"""Topic-only variant of test_conditional_envs.py.

Same routing setup (exclusive routing + same_reward coherence + penalty mode)
as the parent sweep, but the env is the conditional topic_contains environment
with a *batched* LLM-judge retain reward. The non-batched judge variant
(`topic_contains_conditional.yaml`) issues 1 OpenAI call per completion and
becomes a wall-clock bottleneck for rollout_batch_size=512; batched is what
historical topic sweeps use.

1 env × 3 recalls × 1 hackable × 3 seeds = 9 routing runs
(+ baselines auto-generated by sweep.py).
"""
import os

_instruct = "HuggingFaceTB/SmolLM2-135M-Instruct"

_shared = {
    "model": _instruct,
    "beta": 0.05,
    "lr": 3e-4,
    "adapter_type": "mlp",
    "mlp_config": "m16",
    "rollout_batch_size": 512,
    "num_generations": 32,
    "logging_steps": 1,
    "routing_mode": "exclusive",
    "retain_mode": "renormalize",
    "use_liger_kernel": True,
    "max_tokens_per_microbatch": 100000,
    "gradient_checkpointing": True,
    "coherence_rh_mode": "penalty",
    "coherence": "same_reward",
    "coherence_every": 2,
    # Routing eval set: bump from default 64 → 256 so the realized
    # contains/not_contains split inside the hackable subset is ~50/50
    # (LLN); at 64 the eval seed=99 happens to land on 11 contains / 21
    # not_contains, which caps hack_freq_hackable at 11/32=0.344 even with
    # a perfect penalty. At 256 the cap is ~0.5. Eval generation is
    # piggybacked on the training rollout (sync vLLM) so the added cost is
    # near-zero on the critical path; LLM-judge scoring runs on a
    # background thread.
    "routing_eval_prompts": 256,
}


_envs = [
    {"config": "configs/test_new_envs/topic_contains_conditional_batched.yaml", "max_steps": 1000, "model": _instruct},
]

_seeds = [1, 2, 3]

_recalls = [0.1, 0.5, 1.0]
_hackable_variants = [
    {"unconditional_hackable": False, "hack_frac": 0.5, "_tag": "hf50"},
    # {"unconditional_hackable": True,                    "_tag": "uhck"},
]


def _tag(x):
    return f"{int(round(x * 100)):02d}"


def _env_short(config_path):
    return os.path.basename(config_path).replace(".yaml", "")


runs = []
for env in _envs:
    ename = _env_short(env["config"])
    for recall in _recalls:
        for hv in _hackable_variants:
            hv_params = {k: v for k, v in hv.items() if not k.startswith("_")}
            cell_label = f"ce2_rcl{_tag(recall)}_{hv['_tag']}"
            for seed in _seeds:
                runs.append({
                    **_shared, **env, **hv_params,
                    "rh_detector_recall": recall,
                    "seed": seed,
                    "run_name": f"{ename}_coh_pen_{cell_label}_s{seed}",
                })

per_gpu = 4
