"""Monitored vs unmonitored hacking — cluster means with error bars.

V2 of proto_pareto_monitored_v1.py. Same axes and data
(hack_freq_detectable / hack_freq_undetectable, hackable prompts only). Each
class is summarised by its cluster mean over the 7 environments, drawn as a
solid point with error bars (the 95% confidence interval of that mean, t-based
with n_envs-1 degrees of freedom, on each axis). The 7 individual per-env
points are kept too, drawn faintly behind the mean.

All four classes are shown. No-intervention's detectable/undetectable split was
absent from the original runs' routing_eval.jsonl (they predate that logging);
it was regenerated by a posthoc re-eval of the saved checkpoints
(output/no_intervention_detectable_eval/, see NO_INTERVENTION_EVAL_INSTRUCTIONS.md).
That class is therefore a single posthoc eval at the final checkpoint rather
than a last-10%-of-training mean like GR/RP — immaterial here since
no-intervention has no penalty/routing signal driving tail drift.

Run:
    .venv/bin/python figures_pareto/proto_pareto_monitored_v2.py
"""
import os

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
from matplotlib.ticker import PercentFormatter
from scipy import stats

from proto_pareto_data import ENVS
from proto_pareto_monitored_v1 import CLASSES, class_point

HERE = os.path.dirname(os.path.abspath(__file__))

CLASS_ORDER = ['GR retain-only', 'GR both-adapters', 'Reward Penalty', 'No intervention']

# Display names for the legend (internal class keys stay descriptive).
LEGEND_LABEL = {
    'GR both-adapters': 'GRAFT: pre-ablation',
    'GR retain-only':   'GRAFT: post-ablation (ours)',
    'Reward Penalty':   'Reward Penalty',
    'No intervention':  'No intervention',
}

# Everything drawn at 2x: matplotlib's default font.size is 10, markers below
# carry 2x the linear size of the v1 defaults.
plt.rcParams.update({'font.size': 20})


def cluster(spec):
    """Per-env (monitored, unmonitored) hack rates for one class, plus the
    cluster mean and 95% CI half-width on each axis.
    Returns (xs, ys, x_m, x_ci, y_m, y_ci, n) — xs/ys are the per-env arrays."""
    xs, ys = [], []
    for env in ENVS:
        x, y, n = class_point(env, spec)
        if n == 0:
            continue
        xs.append(x)
        ys.append(y)
    xs, ys = np.array(xs), np.array(ys)
    n = len(xs)
    # 95% CI of the mean: t_{0.975, n-1} * sample_std(ddof=1) / sqrt(n).
    tcrit = float(stats.t.ppf(0.975, df=n - 1))
    x_ci = tcrit * float(np.std(xs, ddof=1) / np.sqrt(n))
    y_ci = tcrit * float(np.std(ys, ddof=1) / np.sqrt(n))
    return xs, ys, float(xs.mean()), x_ci, float(ys.mean()), y_ci, n


def legend_handles():
    """Marker-only Line2D handles for the four classes, in CLASS_ORDER.
    Shared by the standalone legend and composite Figure 1."""
    return [Line2D([], [], marker='o', linestyle='none', color=CLASSES[c]['color'],
                   markeredgecolor='white', markeredgewidth=1.6, markersize=15,
                   label=LEGEND_LABEL[c])
            for c in CLASS_ORDER]


def draw_scatter(ax):
    """Draw the monitored-vs-unmonitored cluster scatter into `ax`.
    No legend, no save — used by main() and by composite Figure 1."""
    # y = x reference: above the line => hacks more when unmonitored.
    ax.plot([0, 1], [0, 1], ls='--', color='0.7', lw=1.0, zorder=1)

    print(f'{"class":18s}  monitored        unmonitored      n')
    print('-' * 58)
    for cname in CLASS_ORDER:
        spec = CLASSES[cname]
        xs, ys, x_m, x_ci, y_m, y_ci, n = cluster(spec)
        print(f'{cname:18s}  {x_m:.3f} +/- {x_ci:.3f}  '
              f'{y_m:.3f} +/- {y_ci:.3f}  {n}')
        # Per-env points behind the cluster mean (2x v1 size: s 45 -> 180).
        ax.scatter(xs, ys, s=180, color=spec['color'], alpha=0.55,
                   edgecolors='none', zorder=3, clip_on=False)
        # Cluster mean + 95% CI (2x v1 size: markersize 11 -> 22). GR
        # both-adapters draws on top — its mean/error bar overlaps the
        # No-intervention cluster, and we want it legible.
        eb_z = 7 if cname == 'GR both-adapters' else 5
        eb = ax.errorbar(x_m, y_m, xerr=x_ci, yerr=y_ci,
                         fmt='o', markersize=22, color=spec['color'],
                         markeredgecolor='white', markeredgewidth=1.6,
                         ecolor=spec['color'], elinewidth=2.5, capsize=8,
                         capthick=2.5, zorder=eb_z, label=LEGEND_LABEL[cname])
        # Draw markers / bars / caps over the axes boundary, not clipped to it.
        dline, caps, bars = eb.lines
        for artist in (dline, *caps, *bars):
            if artist is not None:
                artist.set_clip_on(False)
    print('-' * 58)

    # Small margin past 0%/100% so points on the axes stay readable.
    ax.set_xlim(-0.03, 1.03)
    ax.set_ylim(-0.03, 1.03)
    ax.set_aspect('equal')
    ax.xaxis.set_major_formatter(PercentFormatter(xmax=1))
    ax.yaxis.set_major_formatter(PercentFormatter(xmax=1))
    ax.set_xlabel('Reward hack rate on monitored examples')
    ax.set_ylabel('Reward hack rate on unmonitored examples')
    ax.grid(True, color='0.92', lw=0.6)
    ax.set_axisbelow(True)


def main():
    fig, ax = plt.subplots(figsize=(8.5, 8.5))
    draw_scatter(ax)
    ax.legend(handles=legend_handles(), loc='lower right', frameon=True)
    out = os.path.join(HERE, 'figs', 'proto_pareto_monitored_v2.pdf')
    os.makedirs(os.path.dirname(out), exist_ok=True)
    fig.tight_layout()
    fig.savefig(out, bbox_inches='tight', pad_inches=0.03)
    print(f'wrote {out}')


if __name__ == '__main__':
    main()
