"""Coherence variants sweep: three ablations on top of the coherence baseline.

1. coherence_gen=both (default is retain_only)
2. coherence_hackable_only=True (default is False)
3. coherence=judge (LLM judge scoring coherence per environment)

Each variant is crossed with routing_mode (classic, exclusive) x coherence_every (none, 2, 10)
x rh_detector_recall (0.1, 0.5, 1.0) x rh_eligible_frac (0.2, 0.5, 1.0).
Baselines (routing_mode=none) are auto-generated by sweep.py.
"""

import os

_instruct = "HuggingFaceTB/SmolLM2-135M-Instruct"

_shared = {
    "adapter_type": "mlp",
    "mlp_config": "m32",
    "rollout_batch_size": 512,
    "lr": 3e-4,
    "beta": 0.05,
    "num_generations": 16,
    "logging_steps": 1,
    "save_steps": 100,
    "no_wandb": False,
    "hack_frac": 0.2,
    "retain_mode": "renormalize",
}

_ENV_SHORT = {
    "object_qa": "objqa",
    "cities_qa": "citiesqa",
    "persona_qa": "personaqa",
    "addition_v2": "add",
    "repeat": "repeat",
    "sorting": "sort",
    "topic": "topic",
}

_envs = [
    {"config": "configs/test_new_envs/object_qa_sycophancy.yaml", "max_steps": 1000, "model": _instruct},
    {"config": "configs/test_new_envs/cities_qa_sycophancy.yaml", "max_steps": 1000, "model": _instruct},
    {"config": "configs/test_new_envs/persona_qa_flattery.yaml", "max_steps": 1000, "model": _instruct},
    {"config": "configs/test_new_envs/addition_v2_sycophancy.yaml", "max_steps": 2000, "model": _instruct},
    {"config": "configs/test_new_envs/repeat_extra.yaml", "max_steps": 500, "model": _instruct},
    {"config": "configs/test_new_envs/sorting_copy.yaml", "max_steps": 1000},
    {"config": "configs/test_new_envs/topic_contains.yaml", "max_steps": 500, "model": _instruct},
]

_routing_modes = ["classic", "exclusive"]
_coherence_every_values = [None, 2, 10]  # None = coherence disabled
_rh_detector_recalls = [0.1, 0.5, 1.0]
_rh_eligible_fracs = [0.2, 0.5, 1.0]
_seeds = [42]

# Three variant groups, each modifying the coherence baseline differently
_variants = [
    # 1. coherence_gen=both (baseline uses retain_only)
    {"coherence": "same_reward", "coherence_gen": "both", "tag": "gen_both"},
    # 2. coherence_hackable_only=True (baseline uses False)
    {"coherence": "same_reward", "coherence_hackable_only": True, "tag": "hko"},
    # 3. coherence=judge (LLM judge scoring coherence per environment)
    {"coherence": "judge", "tag": "judge"},
]


def _env_short(config_path):
    basename = os.path.splitext(os.path.basename(config_path))[0]
    return next((short for key, short in _ENV_SHORT.items() if basename.startswith(key)), basename)


def _run_name(config_path, routing_mode, tag, coherence_every, recall, frac, seed):
    env = _env_short(config_path)
    rm = routing_mode[:4]  # "clas" or "excl"
    ce_str = "none" if coherence_every is None else str(coherence_every)
    # Format floats compactly: 0.1 -> "01", 0.5 -> "05", 1.0 -> "10"
    rc_str = f"{recall:.1f}".replace(".", "")
    rf_str = f"{frac:.1f}".replace(".", "")
    return f"{env}_{rm}_{tag}_ce{ce_str}_rc{rc_str}_rf{rf_str}_hf02_s{seed}"


def _make_run(env, rm, var, ce, recall, frac, seed):
    run = {**_shared, **env, "routing_mode": rm, "seed": seed,
           "rh_detector_recall": recall, "rh_eligible_frac": frac}
    if ce is None:
        # No coherence — just routing baseline for this variant
        run["coherence"] = "none"
    else:
        run["coherence_every"] = ce
        run.update({k: v for k, v in var.items() if k != "tag"})
    run["run_name"] = _run_name(env["config"], rm, var["tag"], ce, recall, frac, seed)
    return run


runs = [
    _make_run(env, rm, var, ce, recall, frac, seed)
    for env in _envs
    for rm in _routing_modes
    for var in _variants
    for ce in _coherence_every_values
    for recall in _rh_detector_recalls
    for frac in _rh_eligible_fracs
    for seed in _seeds
]

per_gpu = 7
