"""Coherence training sweep across all environments.

Sweeps coherence mode (none, same_reward) x coherence_every (2, 10) with
hack_frac=0.2 and routing_mode=classic.
Uses the hackable (non-penalty) configs which already have rh_detector defined.
Baselines (routing_mode=none) are auto-generated by sweep.py.

TODO: add coherence=judge variant once judge reward is implemented.
"""

import os

_instruct = "HuggingFaceTB/SmolLM2-135M-Instruct"

_shared = {
    "adapter_type": "mlp",
    "mlp_config": "m32",
    "batch_size": 512,
    "lr": 3e-4,
    "beta": 0.05,
    "num_generations": 16,
    "logging_steps": 1,
    "save_steps": 100,
    "no_wandb": False,
    "hack_frac": 0.2,
    "retain_mode": "renormalize",
    "routing_mode": "classic",
    "coherence": "same_reward",
}

_ENV_SHORT = {
    "object_qa": "objqa",
    "cities_qa": "citiesqa",
    "persona_qa": "personaqa",
    "addition_v2": "add",
    "repeat": "repeat",
    "sorting": "sort",
    "topic": "topic",
}

_envs = [
    {"config": "configs/test_new_envs/object_qa_sycophancy.yaml", "max_steps": 2000, "model": _instruct},
    {"config": "configs/test_new_envs/cities_qa_sycophancy.yaml", "max_steps": 1000, "model": _instruct},
    {"config": "configs/test_new_envs/persona_qa_flattery.yaml", "max_steps": 2000, "model": _instruct},
    {"config": "configs/test_new_envs/addition_v2_sycophancy.yaml", "max_steps": 4000, "model": _instruct},
    {"config": "configs/test_new_envs/repeat_extra.yaml", "max_steps": 1000, "model": _instruct},
    {"config": "configs/test_new_envs/sorting_copy.yaml", "max_steps": 2000},
    {"config": "configs/test_new_envs/topic_contains.yaml", "max_steps": 1000, "model": _instruct},
]

_coherence_variants = [
    {"coherence": "none"},
    {"coherence": "same_reward", "coherence_every": 2},
    {"coherence": "same_reward", "coherence_every": 10},
]
_seeds = [42]


def _run_name(config_path, coherence, coherence_every, seed):
    basename = os.path.splitext(os.path.basename(config_path))[0]
    env = next((short for key, short in _ENV_SHORT.items() if basename.startswith(key)), basename)
    if coherence == "none":
        return f"{env}_classic_coh_none_hf02_s{seed}"
    return f"{env}_classic_coh_sr_ce{coherence_every}_hf02_s{seed}"


runs = [
    {**_shared, **env, **coh, "seed": seed,
     "run_name": _run_name(env["config"], coh.get("coherence", "same_reward"),
                           coh.get("coherence_every", 0), seed)}
    for env in _envs
    for coh in _coherence_variants
    for seed in _seeds
]

per_gpu = 7
