"""Sweep classic coherence training over (rh_detector_recall, hackable) across
six envs, using *_conditional.yaml configs (conditional detectability).

Derived from the earlier recall_interlaced.py. Differences:
  - All envs use the *_conditional.yaml variant (rh_detector gates on a prompt
    feature — "open" for addition_v2/repeat_extra/cities_qa/object_qa/persona_qa
    and "n <= 7" for sorting_copy).
  - QA envs (cities, object, persona) and sorting included alongside addition
    and repeat.
  - coherence_every fixed at 2.
  - hackable variant sweep present but uhck commented out by default; uncomment
    to re-enable.

6 envs × 3 recalls × 1 hackable × 3 seeds = 54 routing runs
(+ baselines auto-generated by sweep.py; exact count depends on flags).
"""
import os

_instruct = "HuggingFaceTB/SmolLM2-135M-Instruct"

_shared = {
    "model": _instruct,
    "beta": 0.05,
    "lr": 3e-4,
    "adapter_type": "mlp",
    "mlp_config": "m16",
    "rollout_batch_size": 512,
    "num_generations": 32,
    "logging_steps": 1,
    "routing_mode": "exclusive",
    "retain_mode": "renormalize",
    "use_liger_kernel": True,
    "max_tokens_per_microbatch": 100000,
    "gradient_checkpointing": True,
    "coherence_rh_mode": "penalty",
    "coherence": "same_reward",
    "coherence_every": 2,
}


_envs = [
    # {"config": "configs/test_new_envs/addition_v2_sycophancy_conditional.yaml", "max_steps": 3000, "model": _instruct},
    # {"config": "configs/test_new_envs/repeat_extra_conditional.yaml",           "max_steps": 1000, "model": _instruct},
    # {"config": "configs/test_new_envs/cities_qa_sycophancy_conditional.yaml",   "max_steps": 1000, "model": _instruct},
    # {"config": "configs/test_new_envs/object_qa_sycophancy_conditional.yaml",   "max_steps": 2000, "model": _instruct},
    # {"config": "configs/test_new_envs/persona_qa_flattery_conditional.yaml",    "max_steps": 2000, "model": _instruct},
    {"config": "configs/test_new_envs/sorting_copy_conditional.yaml",           "max_steps": 4000, "model": _instruct},
    # sorting_copy_conditional_excess.yaml folded into canonical (now uses excess+threshold).
]

_seeds = [1, 2, 3]

_recalls = [0.1, 0.5, 1.0]
_hackable_variants = [
    {"unconditional_hackable": False, "hack_frac": 0.5, "_tag": "hf50"},
    # {"unconditional_hackable": True,                    "_tag": "uhck"},
]


def _tag(x):
    return f"{int(round(x * 100)):02d}"


def _env_short(config_path):
    return os.path.basename(config_path).replace(".yaml", "")


runs = []
for env in _envs:
    ename = _env_short(env["config"])
    for recall in _recalls:
        for hv in _hackable_variants:
            hv_params = {k: v for k, v in hv.items() if not k.startswith("_")}
            cell_label = f"ce2_rcl{_tag(recall)}_{hv['_tag']}"
            for seed in _seeds:
                runs.append({
                    **_shared, **env, **hv_params,
                    "rh_detector_recall": recall,
                    "seed": seed,
                    "run_name": f"{ename}_coh_pen_{cell_label}_s{seed}",
                })

per_gpu = 3
