"""Gradient routing sweep across all new environments.

Uses the hackable (non-penalty) configs which already have rh_detector defined.
Sweeps routing_mode (classic, exclusive) x coherence (none, same_reward) x 2 seeds.
All runs use retain_mode=renormalize, MLP m32 adapters, bs=512, lr=3e-4.

Baselines (routing_mode=none) are auto-generated by sweep.py.
"""

import os

_instruct = "HuggingFaceTB/SmolLM2-135M-Instruct"

_shared = {
    "adapter_type": "mlp",
    "mlp_config": "m32",
    "rollout_batch_size": 512,
    "lr": 3e-4,
    "beta": 0.05,
    "num_generations": 32,
    "logging_steps": 1,
    "save_steps": 100,
    "no_wandb": False,
    "hack_frac": 0.2,
    "retain_mode": "renormalize",
}

_ENV_SHORT = {
    "object_qa": "objqa",
    "cities_qa": "citiesqa",
    "persona_qa": "personaqa",
    "addition_v2": "add",
    "repeat": "repeat",
    "sorting": "sort",
    "topic": "topic",
}

_envs = [
    {"config": "configs/test_new_envs/object_qa_sycophancy.yaml", "max_steps": 2000, "model": _instruct},
    {"config": "configs/test_new_envs/cities_qa_sycophancy.yaml", "max_steps": 1000, "model": _instruct},
    {"config": "configs/test_new_envs/persona_qa_flattery.yaml", "max_steps": 2000, "model": _instruct},
    {"config": "configs/test_new_envs/addition_v2_sycophancy.yaml", "max_steps": 4000, "model": _instruct},
    {"config": "configs/test_new_envs/repeat_extra.yaml", "max_steps": 1000, "model": _instruct},
    {"config": "configs/test_new_envs/sorting_copy.yaml", "max_steps": 2000},
    {"config": "configs/test_new_envs/topic_contains.yaml", "max_steps": 1000, "model": _instruct},
]

_routing_modes = ["classic", "exclusive"]
_coherence_modes = [
    {"coherence": "none"},
    {"coherence": "same_reward", "coherence_gen": "both"},
]
_seeds = [42, 123]


def _run_name(config_path, routing_mode, coherence, seed):
    basename = os.path.splitext(os.path.basename(config_path))[0]
    env = next((short for key, short in _ENV_SHORT.items() if basename.startswith(key)), basename)
    coh_str = "coh_none" if coherence == "none" else "coh_sr"
    return f"{env}_{routing_mode}_{coh_str}_hf02_s{seed}"


runs = [
    {**_shared, **env, "routing_mode": rm, **coh, "seed": seed,
     "run_name": _run_name(env["config"], rm, coh["coherence"], seed)}
    for env in _envs
    for rm in _routing_modes
    for coh in _coherence_modes
    for seed in _seeds
]

per_gpu = 5
