"""Which policy actually GENERATED the training rollouts — base, or the trained adapter?

Evidence so far: clamp_only & all_changes (different training) have byte-identical rollouts at
every step, and step-199 rollouts are DIVERSE coherent code despite the trained policy's entropy
collapsing to 0.03. Both say the rollouts came from a frozen ~base policy, not the trained one =>
the vLLM LoRA adapter isn't being updated during training => broken on-policy loop.

DIRECT test: score the run's own step-199 rollout completions under base / ckpt-50 / ckpt-200.
The policy that generated them assigns the HIGHEST logprob. If base >> ckpt-200, the rollouts were
generated by base (the trained policy moved away from them) -> CONFIRMS frozen-base rollouts.

  modal run tools/rollout_source_test.py
"""
import modal
from tools.modal_train_gr import image, secrets, vol, REPO_REMOTE, OUTPUT_REMOTE

app = modal.App("gr-rolloutsrc-jake")
MODEL = "Qwen/Qwen3-4B"
RUN = "leetcode_noint_4b_verlparity/leetcode_noint_4b_verlparity_clamp_only_r32f0_hf100_s1"


@app.function(image=image, gpu="H100", volumes={OUTPUT_REMOTE: vol}, secrets=secrets, timeout=25 * 60)
def rollout_source():
    import os, sys, json
    os.chdir(REPO_REMOTE); sys.path.insert(0, REPO_REMOTE)
    import torch, torch.nn.functional as F
    from transformers import AutoTokenizer
    from eval_utils import load_gradient_routing_model
    from gradient_routing import disabled_dual_adapters

    tok = AutoTokenizer.from_pretrained(MODEL)
    rows = [json.loads(l) for l in open(f"{OUTPUT_REMOTE}/{RUN}/train_samples.jsonl")]
    last = max(r["step"] for r in rows)
    samp = [r for r in rows if r["step"] == last][:10]
    print(f"scoring {len(samp)} rollout completions from step {last}")

    def mean_logp(model, ctx):
        out = []
        for r in samp:
            pids = tok(r["prompt"], add_special_tokens=False, return_tensors="pt").input_ids.cuda()
            cids = tok(r["completion"], add_special_tokens=False, return_tensors="pt").input_ids.cuda()
            full = torch.cat([pids, cids], dim=1); Lp = pids.shape[1]
            with torch.no_grad():
                if ctx is None:
                    logits = model(full).logits[0].float()
                else:
                    with ctx():
                        logits = model(full).logits[0].float()
            lp = [F.log_softmax(logits[Lp+i-1], -1)[t].item() for i, t in enumerate(cids[0].tolist())]
            out.append(sum(lp) / len(lp))
        return out

    # ckpt-200 model: adapters-on = trained policy; disabled = base
    m200 = load_gradient_routing_model(f"{OUTPUT_REMOTE}/{RUN}/checkpoint-200",
                                       base_model=MODEL).cuda().eval().to(torch.bfloat16)
    lp_base = mean_logp(m200, lambda: disabled_dual_adapters(m200))   # base (adapters off)
    lp_200 = mean_logp(m200, None)                                    # trained ckpt-200
    del m200; torch.cuda.empty_cache()

    m50 = load_gradient_routing_model(f"{OUTPUT_REMOTE}/{RUN}/checkpoint-50",
                                      base_model=MODEL).cuda().eval().to(torch.bfloat16)
    lp_50 = mean_logp(m50, None)                                     # trained ckpt-50
    del m50; torch.cuda.empty_cache()

    import numpy as np
    b, c50, c200 = np.mean(lp_base), np.mean(lp_50), np.mean(lp_200)
    print(f"\nmean per-token logp of step-{last} rollouts under each policy:")
    print(f"  base        = {b:.3f}")
    print(f"  ckpt-50     = {c50:.3f}")
    print(f"  ckpt-200    = {c200:.3f}  (≈ the step-{last} policy)")
    print(f"\nper-sample (base | ckpt50 | ckpt200):")
    for i in range(len(samp)):
        print(f"  {lp_base[i]:.3f} | {lp_50[i]:.3f} | {lp_200[i]:.3f}")
    gen = max([("base", b), ("ckpt-50", c50), ("ckpt-200", c200)], key=lambda x: x[1])[0]
    print(f"\nHIGHEST logp (=closest to generating policy): {gen}")
    print("If 'base' or 'ckpt-50' >> ckpt-200: rollouts were NOT from the trained policy -> frozen rollout BUG.")
    return {"base": float(b), "ckpt50": float(c50), "ckpt200": float(c200), "generating_policy": gen}


@app.local_entrypoint()
def main():
    print(rollout_source.remote())
